module.exports = [
    { id: 1, name: 'Alice Zhang', role: 'Engineer', city: 'Shanghai', description: 'Frontend engineer with React and React Native experience.' },
    { id: 2, name: 'Bob Li', role: 'Designer', city: 'Beijing', description: 'Visual designer focused on mobile and web interfaces.' },
    { id: 3, name: 'Cindy Wang', role: 'Product Manager', city: 'Guangzhou', description: 'Leads product roadmaps and customer research.' },
    { id: 4, name: 'David Chen', role: 'Backend Engineer', city: 'Shenzhen', description: 'Builds scalable APIs with Node.js and Koa.' },
    { id: 5, name: 'Emily Sun', role: 'QA Engineer', city: 'Hangzhou', description: 'Writes test plans and automation for web apps.' },
    { id: 6, name: 'Frank Liu', role: 'Data Analyst', city: 'Chengdu', description: 'Analyzes user metrics and visualizes trends.' },
    { id: 7, name: 'Grace Yu', role: 'Marketing', city: 'Suzhou', description: 'Runs campaigns and social media strategy.' },
    { id: 8, name: 'Henry Xu', role: 'Support', city: 'Nanjing', description: 'Handles customer feedback and issue triage.' },
    { id: 9, name: 'Ivy Gao', role: 'HR', city: 'Wuhan', description: 'Manages hiring and employee programs.' },
    { id: 10, name: 'Jack Ma', role: 'CEO', city: 'Ningbo', description: 'Oversees strategy and business growth.' },
    { id: 11, name: 'Kelly Wu', role: 'Engineer', city: 'Suzhou', description: 'Full-stack engineer working on web and API services.' },
    { id: 12, name: 'Leo Zhang', role: 'DevOps', city: 'Tianjin', description: 'Maintains infrastructure and CI/CD pipelines.' },
    { id: 13, name: 'Maggie Lin', role: 'Content', city: 'Xi’an', description: 'Creates copy and content for product launches.' },
    { id: 14, name: 'Nancy He', role: 'Researcher', city: 'Qingdao', description: 'Conducts market research and user interviews.' },
    { id: 15, name: 'Oscar Liu', role: 'Support', city: 'Changsha', description: 'Provides technical assistance for clients.' },
    { id: 16, name: 'Polly Zhang', role: 'Engineer', city: 'Suzhou', description: 'Mobile app engineer with iOS and Android experience.' },
    { id: 17, name: 'Quincy Sun', role: 'Finance', city: 'Nanjing', description: 'Manages budgeting and accounting workflows.' },
    { id: 18, name: 'Rachel Yang', role: 'Operations', city: 'Wuxi', description: 'Coordinates cross-functional execution and logistics.' },
    { id: 19, name: 'Steven Ma', role: 'Engineer', city: 'Jinan', description: 'API developer specializing in Express and Koa.' },
    { id: 20, name: 'Tina Xu', role: 'Designer', city: 'Fuzhou', description: 'Creates UX flows and design systems.' },
    { id: 21, name: 'Uma Chen', role: 'Support', city: 'Zhuhai', description: 'Helps customers with onboarding and training.' },
    { id: 22, name: 'Victor Zhou', role: 'Engineer', city: 'Ningbo', description: 'Works on backend microservices and data pipelines.' },
    { id: 23, name: 'Wendy Tang', role: 'HR', city: 'Hefei', description: 'Supports recruitment and employee relations.' },
    { id: 24, name: 'Xavier Sun', role: 'Marketing', city: 'Dongguan', description: 'Drives brand strategy and growth marketing.' },
    { id: 25, name: 'Yvonne Li', role: 'Product', city: 'Changzhou', description: 'Defines product vision and UX requirements.' },
    { id: 26, name: 'Zack Wei', role: 'Engineer', city: 'Kunming', description: 'Builds platform features and integrations.' },
    { id: 27, name: 'Amy Chen', role: 'Designer', city: 'Nanchang', description: 'Designs interfaces for mobile and desktop.' },
    { id: 28, name: 'Benjamin Hu', role: 'Operations', city: 'Lanzhou', description: 'Improves processes and cross-team flow.' },
    { id: 29, name: 'Cathy Mai', role: 'Research', city: 'Haikou', description: 'Studies customer needs and usage patterns.' },
    { id: 30, name: 'Danny Nie', role: 'Engineer', city: 'Xiamen', description: 'Handles system architecture and scalability.' }
];
